import { countryIdentities, providerIdentities } from './identity'
import type { DashboardMock, HealthState, UiScenario } from '../types'

const baseDashboard = (): DashboardMock => ({
  scenario: 'degraded-ria',
  viewState: 'ready',
  providerIdentities: Object.values(providerIdentities),
  countryIdentities: Object.values(countryIdentities),
  summary: {
    globalHealth: '84.6%',
    valueToday: '$18.4M',
    transactionsToday: '42,618',
    p95CreditTime: '4m 18s',
    stuckTransactions: 184,
    activeIncidents: 2,
    lastUpdated: '14:32:18 UTC',
    atRiskValue: '$2.7M',
    topRisk: 'Europe to Nigeria account payouts',
    safeAction: 'Review a 25% new-traffic shift to Thunes.',
    connection: {
      mode: 'polling',
      freshness: 'fresh',
      updatedAt: '14:32:18 UTC',
      nextPollIn: 'Rail health polling: 15s',
    },
    metrics: [
      { label: 'Routes healthy', value: '84.6%', detail: '15 min measured window', trend: '-12.6%', state: 'degraded' },
      { label: 'At-risk value', value: '$2.7M', detail: '184 unsettled transfers', trend: '+$680K', state: 'watch' },
      { label: 'P95 credit time', value: '4m 18s', detail: 'target 90s account payout', trend: '+2m 48s', state: 'degraded' },
      { label: 'Shift candidate', value: '25%', detail: 'new traffic only', trend: 'review needed', state: 'recovery' },
    ],
  },
  dateRange: {
    label: 'Today',
    start: '2026-05-20 00:00 WAT',
    end: '2026-05-20 14:32 WAT',
    timezone: 'Africa/Lagos',
  },
  qaPolicy: {
    name: 'Nigeria account payout QA',
    version: 'QA-NG-ACCT-v4',
    thresholdSeconds: 90,
    warningSeconds: 75,
    scope: 'Direct-to-account inbound Nigeria',
    completedWithinPolicy: '95.8%',
    breachRate: '4.2%',
    weekComparison: '+1.8% vs last week',
    monthComparison: '+3.4% vs 30-day avg',
    updatedAt: '2026-05-20 13:48 WAT',
  },
  operationalStats: [
    {
      label: 'Completed transactions',
      value: '40,918',
      detail: 'credited to destination in selected range',
      weekComparison: '+8.2% vs last week',
      monthComparison: '+14.6% vs 30-day avg',
      state: 'healthy',
    },
    {
      label: 'Stalled or delayed',
      value: '1,700',
      detail: 'over QA threshold or awaiting destination credit',
      weekComparison: '+312 vs last week',
      monthComparison: '-9.1% vs 30-day avg',
      state: 'degraded',
    },
    {
      label: 'Completed on time',
      value: '39,218',
      detail: 'under current 90s QA policy',
      weekComparison: '+1.8% vs last week',
      monthComparison: '+3.4% vs 30-day avg',
      state: 'healthy',
    },
    {
      label: 'Median total time',
      value: '38s',
      detail: 'sender initiation to destination credit',
      weekComparison: '-6s vs last week',
      monthComparison: '-11s vs 30-day avg',
      state: 'healthy',
    },
  ],
  visuals: {
    completionTrend: [
      { label: '07:00', value: 97.2 },
      { label: '08:00', value: 97.8 },
      { label: '09:00', value: 96.9 },
      { label: '10:00', value: 96.4 },
      { label: '11:00', value: 96.1 },
      { label: '12:00', value: 95.9 },
      { label: '13:00', value: 94.6 },
      { label: '14:00', value: 95.8 },
    ],
    volumeTrend: [
      { label: '07', value: 4120 },
      { label: '08', value: 4820 },
      { label: '09', value: 5310 },
      { label: '10', value: 5680 },
      { label: '11', value: 6220 },
      { label: '12', value: 5890 },
      { label: '13', value: 6460 },
      { label: '14', value: 4118 },
    ],
    latencyBands: [
      { label: 'P50', valueSeconds: 38, targetSeconds: 90, state: 'healthy' },
      { label: 'P95', valueSeconds: 258, targetSeconds: 90, state: 'degraded' },
      { label: 'P99', valueSeconds: 464, targetSeconds: 90, state: 'blocked' },
    ],
    exceptionBreakdown: [
      { label: 'Delayed', value: 1284, state: 'degraded' },
      { label: 'Stalled', value: 416, state: 'blocked' },
      { label: 'Recon', value: 31, state: 'watch' },
    ],
    hourHealth: [
      { label: '07', value: 97, state: 'healthy' },
      { label: '08', value: 98, state: 'healthy' },
      { label: '09', value: 97, state: 'healthy' },
      { label: '10', value: 96, state: 'healthy' },
      { label: '11', value: 96, state: 'watch' },
      { label: '12', value: 96, state: 'watch' },
      { label: '13', value: 95, state: 'degraded' },
      { label: '14', value: 96, state: 'watch' },
    ],
  },
  recommendation: {
    title: 'Move 25% of Europe to Nigeria account payouts off Ria.',
    trigger: 'Ria breached the 90s P95 target for 15 minutes and timeout rate reached 12.5%.',
    affectedTraffic: '184 transfers',
    affectedValue: '$2.7M',
    currentRoute: 'Ria -> NIP',
    suggestedRoute: 'Thunes -> NIP',
    nextAction: 'Review policy',
    evidence: 'Latency breach, timeout spike, fresh FX, healthy Thunes acceptance.',
    state: 'degraded',
  },
  corridors: [
    {
      corridor: 'EU -> Nigeria',
      payout: 'Bank account',
      state: 'degraded' as HealthState,
      selectedRoute: 'Ria -> NIP',
      score: 63,
      p95: '4m 18s',
      cost: '0.74%',
      split: '25 / 75',
      recommendation: 'Preview shift',
      risk: 'Provider acceptance lag',
      atRiskValue: '$2.7M',
      owner: 'Payments Ops',
      status: 'Review policy',
    },
    {
      corridor: 'Kenya -> Nigeria',
      payout: 'Local account',
      state: 'recovery' as HealthState,
      selectedRoute: 'PAPSS',
      score: 79,
      p95: '58s',
      cost: '0.68%',
      split: '10 / 90',
      recommendation: 'Hold split',
      risk: 'Recovery testing',
      atRiskValue: '$410K',
      owner: 'Route desk',
      status: 'Monitoring',
    },
    {
      corridor: 'UK -> Nigeria',
      payout: 'Bank account',
      state: 'watch' as HealthState,
      selectedRoute: 'Remitly -> NIP',
      score: 87,
      p95: '49s',
      cost: '0.91%',
      split: '60 / 40',
      recommendation: 'Watch lag',
      risk: 'Callback delay',
      atRiskValue: '$930K',
      owner: 'Provider ops',
      status: 'Watching lag',
    },
    {
      corridor: 'US -> Nigeria',
      payout: 'Bank account',
      state: 'healthy' as HealthState,
      selectedRoute: 'Thunes -> NIP',
      score: 94,
      p95: '31s',
      cost: '0.82%',
      split: '72 / 28',
      recommendation: 'Route more',
      risk: 'Inside policy',
      atRiskValue: '$0',
      owner: 'Route engine',
      status: 'Healthy route',
    },
  ],
  providerScores: [
    {
      rank: 1,
      provider: 'Thunes',
      corridor: 'United States -> Nigeria',
      successRate: '99.1%',
      p50: '14s',
      p95: '31s',
      p99: '58s',
      stuckRate: '0.04%',
      settlementExceptions: 2,
      state: 'healthy',
      supportSla: '12m',
      trafficShare: '47%',
    },
    {
      rank: 2,
      provider: 'Remitly',
      corridor: 'UK -> Nigeria',
      successRate: '98.4%',
      p50: '18s',
      p95: '49s',
      p99: '1m 12s',
      stuckRate: '0.09%',
      settlementExceptions: 5,
      state: 'watch',
      supportSla: '18m',
      trafficShare: '24%',
    },
    {
      rank: 3,
      provider: 'PAPSS',
      corridor: 'Kenya -> Nigeria',
      successRate: '96.8%',
      p50: '23s',
      p95: '58s',
      p99: '1m 36s',
      stuckRate: '0.21%',
      settlementExceptions: 4,
      state: 'recovery',
      supportSla: '22m',
      trafficShare: '9%',
    },
    {
      rank: 4,
      provider: 'Ria',
      corridor: 'EU -> Nigeria',
      successRate: '87.5%',
      p50: '46s',
      p95: '4m 18s',
      p99: '7m 44s',
      stuckRate: '1.18%',
      settlementExceptions: 19,
      state: 'degraded',
      supportSla: '41m',
      trafficShare: '20%',
    },
  ],
  transactions: [
    {
      reference: 'IMSI-txn_000000000001',
      providerReference: 'RIA-EU-7K2Q',
      bankReference: 'ACB-NIP-581209',
      senderCountry: 'Germany',
      destinationCountry: 'Nigeria',
      senderCurrency: 'EUR',
      destinationCurrency: 'NGN',
      destinationType: 'Local bank',
      provider: 'Ria',
      route: 'Ria -> NIP',
      amount: 'EUR 2,400',
      senderStartedAt: '14:29:11 UTC',
      destinationCreditedAt: '14:33:29 UTC',
      totalTime: '4m 18s',
      totalTimeSeconds: 258,
      qaLimitSeconds: 90,
      qaStatus: 'delayed',
      state: 'degraded',
      beneficiary: 'Access Bank / 012****549',
      currentOwner: 'Provider ops',
      blocker: 'Provider acceptance breached QA policy before destination credit.',
    },
    {
      reference: 'IMSI-txn_000000000014',
      providerReference: 'THN-US-91A2',
      bankReference: 'GTB-NIP-882104',
      senderCountry: 'United States',
      destinationCountry: 'Nigeria',
      senderCurrency: 'USD',
      destinationCurrency: 'NGN',
      destinationType: 'Local bank',
      provider: 'Thunes',
      route: 'Thunes -> NIP',
      amount: 'USD 950',
      senderStartedAt: '14:28:04 UTC',
      destinationCreditedAt: '14:28:37 UTC',
      totalTime: '33s',
      totalTimeSeconds: 33,
      qaLimitSeconds: 90,
      qaStatus: 'on_time',
      state: 'healthy',
      beneficiary: 'GTBank / 014****771',
      currentOwner: 'Route engine',
      blocker: 'None. Completed under QA policy.',
    },
    {
      reference: 'IMSI-txn_000000031822',
      providerReference: 'RMT-UK-55Q8',
      bankReference: 'UBA-NIP-102981',
      senderCountry: 'United Kingdom',
      destinationCountry: 'Nigeria',
      senderCurrency: 'GBP',
      destinationCurrency: 'NGN',
      destinationType: 'Local bank',
      provider: 'Remitly',
      route: 'Remitly -> NIP',
      amount: 'GBP 850',
      senderStartedAt: '14:21:40 UTC',
      destinationCreditedAt: 'pending',
      totalTime: '10m 52s',
      totalTimeSeconds: 652,
      qaLimitSeconds: 90,
      qaStatus: 'stalled',
      state: 'blocked',
      beneficiary: 'UBA / 208****314',
      currentOwner: 'Bank posting monitor',
      blocker: 'Destination credit has not been confirmed.',
    },
    {
      reference: 'IMSI-txn_000000034410',
      providerReference: 'PAPSS-KE-41B7',
      bankReference: 'FBN-NIP-991430',
      senderCountry: 'Kenya',
      destinationCountry: 'Nigeria',
      senderCurrency: 'KES',
      destinationCurrency: 'NGN',
      destinationType: 'International bank',
      provider: 'PAPSS',
      route: 'PAPSS',
      amount: 'KES 180,000',
      senderStartedAt: '14:18:12 UTC',
      destinationCreditedAt: '14:19:08 UTC',
      totalTime: '56s',
      totalTimeSeconds: 56,
      qaLimitSeconds: 90,
      qaStatus: 'on_time',
      state: 'recovery',
      beneficiary: 'FirstBank / 302****108',
      currentOwner: 'Route desk',
      blocker: 'Recovery check completed under QA policy.',
    },
  ],
  trace: {
    reference: 'IMSI-txn_000000000001',
    providerReference: 'RIA-EU-7K2Q',
    bankReference: 'ACB-NIP-581209',
    beneficiary: 'Access Bank / 012****549',
    corridor: 'EU -> Nigeria',
    amount: 'EUR 2,400',
    senderCountry: 'Germany',
    destinationCountry: 'Nigeria',
    senderCurrency: 'EUR',
    destinationCurrency: 'NGN',
    destinationType: 'Local bank',
    senderStartedAt: '14:29:11 UTC',
    destinationCreditedAt: '14:33:29 UTC',
    totalTime: '4m 18s',
    totalTimeSeconds: 258,
    qaLimitSeconds: 90,
    qaStatus: 'delayed',
    currentState: 'watch',
    currentOwner: 'NIP posting monitor',
    blocker: 'Provider accepted late; bank posting remains inside SLA.',
    safeAction: 'Do not reroute in flight. Keep monitoring settlement match.',
    policyVersion: 'v2026.05.20.14.05',
    fallbackRoutes: ['Thunes -> NIP', 'Remitly -> NIP', 'Manual review'],
    selectedRoute: {
      provider: 'Ria',
      route: 'Ria -> NIP',
      score: 63,
      p95: '4m 18s',
      cost: '0.74%',
      state: 'degraded',
      reason: 'Selected before circuit breaker opened.',
      confidence: 'Medium',
      policyVersion: 'v2026.05.20.14.05',
    },
    rejectedRoutes: [
      { provider: 'Thunes', route: 'Thunes -> NIP', reason: 'Fallback only under live split at decision time.' },
      { provider: 'Remitly', route: 'Remitly -> NIP', reason: 'EUR/NGN FX rate was stale.' },
      { provider: 'PAPSS', route: 'PAPSS', reason: 'EU origin unsupported for account payout.' },
    ],
    scoreInputs: [
      { label: 'Reliability', value: '87.5%', state: 'degraded' },
      { label: 'Speed', value: '4m 18s P95', state: 'degraded' },
      { label: 'Cost', value: '0.74%', state: 'healthy' },
      { label: 'FX age', value: '2 min', state: 'healthy' },
      { label: 'Policy', value: 'allowed at decision', state: 'watch' },
    ],
    timeline: [
      { label: 'Sender initiated', owner: 'Bank channel', status: 'done', time: '14:29:11', duration: '0s', source: 'Bank API', reference: 'IDEMP-9e2' },
      { label: 'Validated', owner: 'imsi-rails', status: 'done', time: '14:29:11', duration: '0.4s', source: 'Validation service', reference: 'VAL-810' },
      { label: 'Route picked', owner: 'Route engine', status: 'done', time: '14:29:12', duration: '1s', source: 'Policy v2026.05.20.14.05', reference: 'DEC-542' },
      { label: 'Provider accepted', owner: 'Ria', status: 'done', time: '14:31:20', duration: '2m 09s', source: 'Provider API', reference: 'RIA-EU-7K2Q', note: 'Late acceptance' },
      { label: 'Bank rail posting', owner: 'NIP', status: 'done', time: '14:31:23', duration: '2m 12s', source: 'Bank adapter', reference: 'ACB-NIP-581209' },
      { label: 'Destination credited', owner: 'Access Bank', status: 'done', time: '14:33:29', duration: '4m 18s', source: 'NIP confirmation', reference: 'ACB-NIP-581209' },
      { label: 'Settlement match', owner: 'Settlement', status: 'pending', time: 'pending', source: 'Reconciliation', reference: 'Batch pending' },
    ],
  },
  latency: {
    filters: {
      provider: 'Ria',
      corridor: 'EU -> Nigeria',
      destinationBank: 'Access Bank',
      window: '15 min',
    },
    summary: {
      endToEnd: '4m 18s',
      target: '90s',
      slowestStep: 'Provider accepted',
      affectedTransactions: 184,
    },
    steps: [
      { label: 'Bank submit', owner: 'Bank channel', durationMs: 420, targetMs: 800, state: 'healthy' },
      { label: 'Validation', owner: 'imsi-rails', durationMs: 260, targetMs: 500, state: 'healthy' },
      { label: 'FX lock', owner: 'Treasury rules', durationMs: 1_800, targetMs: 2_000, state: 'healthy' },
      { label: 'Provider accepted', owner: 'Ria', durationMs: 128_000, targetMs: 30_000, state: 'degraded' },
      { label: 'Webhook callback', owner: 'Ria', durationMs: 84_000, targetMs: 45_000, state: 'watch' },
      { label: 'Bank posting', owner: 'NIP', durationMs: 43_000, targetMs: 60_000, state: 'healthy' },
      { label: 'Settlement file', owner: 'Settlement Ops', durationMs: 62_000, targetMs: 120_000, state: 'healthy' },
    ],
  },
  downtimeEvents: [
    {
      time: '14:04',
      title: 'P95 target missed',
      actor: 'imsi-rails',
      state: 'watch',
      detail: 'Europe to Nigeria account payouts crossed 90s.',
    },
    {
      time: '14:13',
      title: 'Ria route degraded',
      actor: 'Ria adapter',
      state: 'degraded',
      detail: 'Timeouts reached 12.5% in the last 15 min.',
    },
    {
      time: '14:16',
      title: 'Traffic shift previewed',
      actor: 'Ops analyst',
      state: 'recovery',
      detail: '25% to Thunes looked faster with acceptable cost.',
    },
    {
      time: '14:21',
      title: 'Policy draft marked for review',
      actor: 'Policy workflow',
      state: 'watch',
      detail: 'Draft shift is visible in policy review.',
    },
  ],
  incidents: [
    {
      id: 'INC-2026-0520-014',
      title: 'Ria acceptance latency breach',
      severity: 'degraded',
      corridor: 'EU -> Nigeria',
      owner: 'Payments Ops',
      startedAt: '14:04 UTC',
      affectedTransactions: 184,
      affectedValue: '$2.7M',
      rootCause: 'Provider API timeout spike and webhook lag.',
      nextAction: 'Review 25% traffic shift to Thunes.',
      status: 'Review policy',
    },
    {
      id: 'INC-2026-0520-011',
      title: 'PAPSS recovery check',
      severity: 'recovery',
      corridor: 'Kenya -> Nigeria',
      owner: 'Route desk',
      startedAt: '13:20 UTC',
      affectedTransactions: 42,
      affectedValue: '$410K',
      rootCause: 'Recovery testing after settlement lag.',
      nextAction: 'Hold at 10% until P95 remains under 60s for 30 min.',
      status: 'Monitoring',
    },
  ],
  routeConfig: {
    providers: [
      { provider: 'Thunes', route: 'Europe to Nigeria / NIP', enabled: true, state: 'healthy' },
      { provider: 'Remitly', route: 'Europe to Nigeria / NIP', enabled: true, state: 'stale' },
      { provider: 'Ria', route: 'Europe to Nigeria / NIP', enabled: false, state: 'degraded' },
      { provider: 'PAPSS', route: 'Africa corridor only', enabled: true, state: 'recovery' },
    ],
    fallbackRoutes: [
      { rank: 1, provider: 'Thunes', route: 'NIP account payout', state: 'healthy' },
      { rank: 2, provider: 'Remitly', route: 'NIP account payout', state: 'stale' },
      { rank: 3, provider: 'PAPSS', route: 'Cross-border account payout', state: 'recovery' },
      { rank: 4, provider: 'Ria', route: 'NIP account payout', state: 'degraded' },
    ],
    presets: [
      { label: 'Incident shift', active: true, split: '75 / 25 / 0' },
      { label: 'Balanced', active: false, split: '50 / 30 / 20' },
      { label: 'Recovery', active: false, split: '80 / 10 / 10' },
    ],
    weights: [
      { label: 'Reliability', value: 42 },
      { label: 'Speed', value: 28 },
      { label: 'Cost', value: 16 },
      { label: 'FX', value: 14 },
    ],
    impact: {
      successRate: '+6.1%',
      p95: '-2m 47s',
      cost: '+0.08%',
    },
    history: [
      { time: '14:21', actor: 'Policy workflow', summary: 'Marked 25% shift to Thunes for review.' },
      { time: '14:16', actor: 'Ops analyst', summary: 'Previewed 25% shift from Ria to Thunes.' },
      { time: '13:48', actor: 'Treasury lead', summary: 'Raised FX freshness for Europe to Nigeria.' },
    ],
    workflow: {
      scope: [
        { label: 'Corridor', value: 'Europe to Nigeria' },
        { label: 'Payout', value: 'Bank account' },
        { label: 'Destination bank', value: 'Access Bank, UBA, GTBank' },
        { label: 'Amount band', value: 'EUR 0 - 5,000' },
      ],
      currentPolicy: [
        { label: 'Live split', value: 'Ria 75 / Thunes 25' },
        { label: 'Fallback', value: 'Ria, Thunes, Remitly' },
        { label: 'Breaker action', value: 'Alert only' },
        { label: 'FX max age', value: '20 min' },
      ],
      proposedPolicy: [
        { label: 'Live split', value: 'Thunes 75 / Ria 25', changed: true },
        { label: 'Fallback', value: 'Thunes, Remitly, Ria', changed: true },
        { label: 'Breaker action', value: 'Block new Ria traffic', changed: true },
        { label: 'FX max age', value: '10 min', changed: true },
      ],
      validation: [
        { label: 'Affected traffic', value: '184 active / 1,920 next hour', state: 'watch' },
        { label: 'Duplicate payout risk', value: 'New traffic only', state: 'healthy' },
        { label: 'Change mode', value: 'New traffic only', state: 'healthy' },
        { label: 'Current policy', value: 'Recorded', state: 'healthy' },
      ],
      change: {
        reason: 'Ria missed 90s P95 target for 15 minutes and Thunes is healthy with fresh FX.',
      },
    },
  },
  policySimulationSamples: [
    {
      reference: 'SIM-ROUTE-1042',
      corridor: 'EU -> Nigeria',
      origin: 'Germany',
      destination: 'Access Bank',
      amount: 'EUR 2,400',
      payout: 'Bank account',
      current: {
        provider: 'Ria',
        route: 'Ria -> NIP',
        score: 63,
        p95: '4m 18s',
        cost: '0.74%',
        state: 'degraded',
        reason: 'Cheapest route but currently degraded.',
        confidence: 'Low',
        policyVersion: 'v2026.05.20.14.05',
      },
      proposed: {
        provider: 'Thunes',
        route: 'Thunes -> NIP',
        score: 91,
        p95: '37s',
        cost: '0.82%',
        state: 'healthy',
        reason: 'Healthy route with fresh FX and lower intervention risk.',
        confidence: 'High',
        policyVersion: 'draft-v2026.05.20.14.21',
      },
      rejectedRoutes: [
        { provider: 'Ria', route: 'Ria -> NIP', reason: 'Circuit breaker blocks new traffic.' },
        { provider: 'Remitly', route: 'Remitly -> NIP', reason: 'EUR/NGN FX is stale.' },
        { provider: 'PAPSS', route: 'PAPSS', reason: 'EU account payouts are not supported.' },
      ],
      reportMetrics: [
        { label: 'Better route', value: '386', detail: 'of 500 historical transactions' },
        { label: 'P95 change', value: '-3m 41s', detail: 'vs live rules' },
        { label: 'Cost change', value: '+0.08%', detail: 'effective cost' },
      ],
      reportRows: [
        { bucket: 'Healthy payout', currentRoute: 'Ria -> NIP', proposedRoute: 'Thunes -> NIP', result: 'Faster route' },
        { bucket: 'Stale FX', currentRoute: 'Ria -> NIP', proposedRoute: 'Hold for refresh', result: 'Wait for FX' },
        { bucket: 'Manual review', currentRoute: 'Ria -> NIP', proposedRoute: 'No change', result: 'Same decision' },
      ],
    },
  ],
  fxCostBoard: {
    corridor: 'EU -> Nigeria',
    pair: 'EUR/NGN',
    window: '15 min',
    refreshedAt: '14:31 UTC',
    cheapestProvider: 'Ria',
    recommendedProvider: 'Thunes',
    rateAlert: 'Remitly rate is 22 min old. New EUR/NGN traffic is blocked until refresh.',
    decision: 'Ria is cheapest, but the route is degraded. Thunes costs +0.08% and is healthy, so it is the selected eligible route.',
    routes: [
      {
        provider: 'Thunes',
        route: 'Thunes -> NIP',
        pair: 'EUR/NGN',
        rate: '1,721.40',
        updatedAt: '14:31 UTC',
        state: 'healthy',
        fee: '0.32%',
        spread: '0.50%',
        effectiveCost: '0.82%',
        payoutTime: '37s',
        cheapest: false,
        recommended: true,
        note: 'Healthy route with fresh FX.',
      },
      {
        provider: 'Ria',
        route: 'Ria -> NIP',
        pair: 'EUR/NGN',
        rate: '1,724.10',
        updatedAt: '14:30 UTC',
        state: 'degraded',
        fee: '0.26%',
        spread: '0.48%',
        effectiveCost: '0.74%',
        payoutTime: '4m 18s',
        cheapest: true,
        recommended: false,
        note: 'Cheapest, but too slow right now.',
      },
      {
        provider: 'Remitly',
        route: 'Remitly -> NIP',
        pair: 'EUR/NGN',
        rate: '1,718.90',
        updatedAt: '14:09 UTC',
        state: 'stale',
        fee: '0.30%',
        spread: '0.56%',
        effectiveCost: '0.86%',
        payoutTime: '58s',
        cheapest: false,
        recommended: false,
        note: 'Rate is stale.',
      },
      {
        provider: 'PAPSS',
        route: 'PAPSS',
        pair: 'EUR/NGN',
        rate: '1,716.20',
        updatedAt: '14:28 UTC',
        state: 'watch',
        fee: '0.18%',
        spread: '0.65%',
        effectiveCost: '0.83%',
        payoutTime: '1m 12s',
        cheapest: false,
        recommended: false,
        note: 'Not eligible for this payout.',
      },
    ],
  },
  reconciliation: [
    { reference: 'REC-7781', provider: 'Ria', amount: 'EUR 2,400', age: '42m', reason: 'Late provider settlement file', owner: 'Settlement Ops', state: 'watch' },
    { reference: 'REC-7784', provider: 'Ria', amount: 'EUR 910', age: '31m', reason: 'Provider accepted, bank credit pending', owner: 'Rail status desk', state: 'degraded' },
    { reference: 'REC-7792', provider: 'Remitly', amount: 'GBP 850', age: '18m', reason: 'FX timestamp mismatch', owner: 'Treasury Ops', state: 'stale' },
  ],
  auditEvents: [
    { time: '14:21:44', actor: 'Ops analyst', action: 'Marked draft for review', object: 'Europe to Nigeria policy draft', reason: 'Ria P95 breach', state: 'watch' },
    { time: '14:16:08', actor: 'Ops analyst', action: 'Previewed traffic shift', object: 'Ria to Thunes 25%', reason: 'Latency breach', state: 'recovery' },
    { time: '14:13:22', actor: 'Circuit breaker', action: 'Marked degraded', object: 'Ria -> NIP', reason: 'Timeout rate 12.5%', state: 'degraded' },
    { time: '13:48:12', actor: 'Treasury lead', action: 'Changed FX freshness', object: 'EUR/NGN max age', reason: 'Stale-rate control', state: 'healthy' },
  ],
  routingContracts: [
    {
      id: 'CON-UK-NG-01',
      partner: 'Sterling Send (UK)',
      partnerType: 'IMTO',
      originCountry: 'United Kingdom',
      destinationCountry: 'Nigeria',
      corridor: 'United Kingdom -> Nigeria',
      payoutMethods: 'Bank account, Wallet, Paystack',
      endpointCount: 5,
      monthlyVolume: 'GBP 6.8M',
      deliveryReliability: '98.4%',
      creditSla: '90s account / 30s wallet',
      slaBreachRate: '1.6%',
      lastSettlement: 'Today 13:40 UTC',
      availableLimit: 'GBP 1.8M remaining',
      settlementModel: 'T+1 prefunded',
      prefundStatus: '82% available',
      cutoffWindow: '18:00 UTC',
      openExceptions: 3,
      oldestOpenCredit: '12m 04s',
      nextReview: 'Partner SLA review at 16:00 UTC',
      state: 'healthy',
      status: 'Live',
      owner: 'Operations desk',
      note: 'Primary UK landing contract. NIP, Paystack, and wallet rails active.',
      endpoints: [
        { name: 'Fidelity Bank core (NIP)', kind: 'Local bank', rail: 'NIP', reach: 'All NGN banks', reliability: '99.1%', p95Credit: '41s', openCredits: 1, callbackLag: '8s', settlementLag: '2m', owner: 'Settlement Ops', state: 'healthy' },
        { name: 'Paystack transfer', kind: 'Payment gateway', rail: 'Paystack Transfer', reach: 'NUBAN and supported wallets', reliability: '96.9%', p95Credit: '3m 18s', openCredits: 1, callbackLag: '5m 20s', settlementLag: '4m', owner: 'Paystack monitor', state: 'watch' },
        { name: 'OPay wallet', kind: 'Fintech wallet', rail: 'OPay API', reach: '28M wallets', reliability: '98.7%', p95Credit: '22s', openCredits: 1, callbackLag: '12s', settlementLag: '1m', owner: 'Compliance', state: 'healthy' },
        { name: 'Moniepoint MFB', kind: 'MFB', rail: 'Moniepoint API', reach: '5M accounts', reliability: '97.2%', p95Credit: '2m 44s', openCredits: 0, callbackLag: '44s', settlementLag: '3m', owner: 'Provider callback desk', state: 'watch' },
        { name: 'PalmPay wallet', kind: 'Fintech wallet', rail: 'PalmPay API', reach: '25M wallets', reliability: '98.0%', p95Credit: '26s', openCredits: 0, callbackLag: '15s', settlementLag: '2m', owner: 'Operations desk', state: 'healthy' },
      ],
    },
    {
      id: 'CON-GR-NG-02',
      partner: 'Hellenic Remit (Greece)',
      partnerType: 'Foreign bank',
      originCountry: 'Greece',
      destinationCountry: 'Nigeria',
      corridor: 'Greece -> Nigeria',
      payoutMethods: 'Bank account, MFB',
      endpointCount: 3,
      monthlyVolume: 'EUR 2.1M',
      deliveryReliability: '94.8%',
      creditSla: '120s account',
      slaBreachRate: '5.2%',
      lastSettlement: 'Today 11:05 UTC',
      availableLimit: 'EUR 420K remaining',
      settlementModel: 'T+2 net settlement',
      prefundStatus: 'Sufficient',
      cutoffWindow: '17:00 UTC',
      openExceptions: 2,
      oldestOpenCredit: '8m 12s',
      nextReview: 'Escalate MFB callback lag if open after 15:00 UTC',
      state: 'watch',
      status: 'Live - monitoring',
      owner: 'Operations desk',
      note: 'MFB last-mile reliability slipping. Watch Moniepoint callback lag.',
      endpoints: [
        { name: 'Fidelity Bank core (NIP)', kind: 'Local bank', rail: 'NIP', reach: 'All NGN banks', reliability: '98.6%', p95Credit: '48s', openCredits: 0, callbackLag: '11s', settlementLag: '2m', owner: 'Settlement Ops', state: 'healthy' },
        { name: 'Moniepoint MFB', kind: 'MFB', rail: 'Moniepoint API', reach: '5M accounts', reliability: '91.4%', p95Credit: '4m 02s', openCredits: 1, callbackLag: '7m 40s', settlementLag: '6m', owner: 'Provider callback desk', state: 'degraded' },
        { name: 'Fairmoney MFB', kind: 'MFB', rail: 'Fairmoney API', reach: '3M accounts', reliability: '95.1%', p95Credit: '3m 30s', openCredits: 1, callbackLag: '1m 18s', settlementLag: '5m', owner: 'Operations desk', state: 'watch' },
      ],
    },
    {
      id: 'CON-UK-NG-03',
      partner: 'Albion Money (UK)',
      partnerType: 'Fintech',
      originCountry: 'United Kingdom',
      destinationCountry: 'Nigeria',
      corridor: 'United Kingdom -> Nigeria',
      payoutMethods: 'Wallet, Agent cash',
      endpointCount: 2,
      monthlyVolume: 'GBP 1.4M',
      deliveryReliability: '99.0%',
      creditSla: '30s wallet',
      slaBreachRate: '1.0%',
      lastSettlement: 'Today 14:10 UTC',
      availableLimit: 'GBP 760K remaining',
      settlementModel: 'T+0 prefunded',
      prefundStatus: '91% available',
      cutoffWindow: '20:00 UTC',
      openExceptions: 1,
      oldestOpenCredit: '11s',
      nextReview: 'Compliance hold review before wallet credit',
      state: 'healthy',
      status: 'Live',
      owner: 'Operations desk',
      note: 'Wallet-first contract. Agent cash network used for unbanked beneficiaries.',
      endpoints: [
        { name: 'OPay wallet', kind: 'Fintech wallet', rail: 'OPay API', reach: '28M wallets', reliability: '99.2%', p95Credit: '14s', openCredits: 1, callbackLag: '9s', settlementLag: '1m', owner: 'Compliance', state: 'healthy' },
        { name: 'Taj agent network', kind: 'Agent network', rail: 'Agent cash', reach: '12K agents', reliability: '96.8%', p95Credit: '2m 05s', openCredits: 0, callbackLag: '30s', settlementLag: '5m', owner: 'Agent desk', state: 'watch' },
      ],
    },
  ],
  creditLegs: [
    {
      reference: 'CRD-90218',
      contractId: 'CON-UK-NG-01',
      partner: 'Sterling Send (UK)',
      partnerReference: 'SS-7741920',
      originCountry: 'United Kingdom',
      destinationCountry: 'Nigeria',
      beneficiary: 'Amaka Obi',
      beneficiaryAccount: 'OPay 805***2210',
      endpoint: 'OPay wallet',
      endpointKind: 'Fintech wallet',
      amount: 'NGN 1,240,000',
      valueAtRisk: 'NGN 0',
      receivedAt: '14:30:02 UTC',
      creditedAt: '14:30:21 UTC',
      elapsed: '19s',
      slaDueAt: '14:30:32 UTC',
      slaState: 'healthy',
      creditState: 'credited',
      state: 'healthy',
      reversal: false,
      reconState: 'Auto-matched',
      evidenceStatus: 'Complete',
      railReference: 'OPAY-WLT-93012',
      bankPostingReference: 'OPAY-CR-778190',
      settlementBatch: 'SET-UK-20260519-044',
      callbackLag: '2s',
      lastCallbackAt: '14:30:23 UTC',
      postingAttempts: 1,
      makerCheckerStatus: 'Not required',
      nextAction: 'No action',
      owner: 'Operations desk',
      blocker: 'None',
      riskFlags: ['Auto-credit verified'],
      evidence: [
        { label: 'Partner instruction', reference: 'SS-7741920', status: 'Matched', owner: 'Sterling Send', state: 'healthy' },
        { label: 'Wallet credit callback', reference: 'OPAY-WLT-93012', status: 'Matched', owner: 'OPay API', state: 'healthy' },
        { label: 'Settlement batch', reference: 'SET-UK-20260519-044', status: 'Matched', owner: 'Settlement Ops', state: 'healthy' },
      ],
      timeline: [
        { label: 'Funds received from partner', owner: 'Sterling Send', status: 'done', time: '14:30:02', source: 'Partner instruction', reference: 'SS-7741920' },
        { label: 'Beneficiary name enquiry', owner: 'OPay API', status: 'done', time: '14:30:08', duration: '6s' },
        { label: 'Credit posted to wallet', owner: 'OPay API', status: 'done', time: '14:30:21', duration: '13s' },
        { label: 'Settlement reconciled', owner: 'Settlement Ops', status: 'done', time: '14:32:00', note: 'Matched on partner + bank reference' },
      ],
    },
    {
      reference: 'CRD-90231',
      contractId: 'CON-GR-NG-02',
      partner: 'Hellenic Remit (Greece)',
      partnerReference: 'HR-330418',
      originCountry: 'Greece',
      destinationCountry: 'Nigeria',
      beneficiary: 'Chidi Eze',
      beneficiaryAccount: 'Moniepoint 701***8814',
      endpoint: 'Moniepoint MFB',
      endpointKind: 'MFB',
      amount: 'NGN 880,000',
      valueAtRisk: 'NGN 880,000',
      receivedAt: '14:24:11 UTC',
      creditedAt: 'Pending',
      elapsed: '8m 12s',
      slaDueAt: '14:26:11 UTC',
      slaState: 'degraded',
      creditState: 'crediting',
      state: 'degraded',
      reversal: false,
      reconState: 'Pending external evidence',
      evidenceStatus: 'Missing final credit callback',
      railReference: 'MPT-TRF-55381',
      bankPostingReference: 'Pending',
      settlementBatch: 'SET-GR-20260519-019',
      callbackLag: '7m 40s',
      lastCallbackAt: '14:24:40 UTC',
      postingAttempts: 1,
      makerCheckerStatus: 'Escalation not started',
      nextAction: 'Escalate callback evidence to Moniepoint after 10m aging',
      owner: 'Provider callback desk',
      blocker: 'Moniepoint callback overdue',
      riskFlags: ['SLA breached', 'Final credit evidence missing'],
      evidence: [
        { label: 'Partner instruction', reference: 'HR-330418', status: 'Matched', owner: 'Hellenic Remit', state: 'healthy' },
        { label: 'Name enquiry', reference: 'MPT-NQ-55380', status: 'Matched', owner: 'Moniepoint API', state: 'healthy' },
        { label: 'Final credit callback', reference: 'MPT-TRF-55381', status: 'Overdue', owner: 'Provider callback desk', state: 'degraded' },
      ],
      timeline: [
        { label: 'Funds received from partner', owner: 'Hellenic Remit', status: 'done', time: '14:24:11', source: 'Partner instruction', reference: 'HR-330418' },
        { label: 'Beneficiary name enquiry', owner: 'Moniepoint API', status: 'done', time: '14:24:19', duration: '8s' },
        { label: 'Credit instruction sent', owner: 'Moniepoint API', status: 'current', time: '14:24:40', note: 'Awaiting credit confirmation callback' },
        { label: 'Settlement reconciled', owner: 'Settlement Ops', status: 'pending', time: '-' },
      ],
    },
    {
      reference: 'CRD-90244',
      contractId: 'CON-GR-NG-02',
      partner: 'Hellenic Remit (Greece)',
      partnerReference: 'HR-330512',
      originCountry: 'Greece',
      destinationCountry: 'Nigeria',
      beneficiary: 'Ngozi Okafor',
      beneficiaryAccount: 'Fairmoney 302***4401',
      endpoint: 'Fairmoney MFB',
      endpointKind: 'MFB',
      amount: 'NGN 1,560,000',
      valueAtRisk: 'NGN 1,560,000',
      receivedAt: '13:58:40 UTC',
      creditedAt: '14:02:10 UTC',
      elapsed: '3m 30s',
      slaDueAt: '14:00:40 UTC',
      slaState: 'watch',
      creditState: 'reversal_pending',
      state: 'watch',
      reversal: true,
      reconState: 'Exception review required',
      evidenceStatus: 'Reversal approval required',
      railReference: 'FMNY-TRF-44190',
      bankPostingReference: 'FMNY-RET-44091',
      settlementBatch: 'SET-GR-20260519-019',
      callbackLag: '38s',
      lastCallbackAt: '14:08:55 UTC',
      postingAttempts: 1,
      makerCheckerStatus: 'Maker submitted',
      nextAction: 'Checker approval required before partner return',
      owner: 'Operations desk',
      blocker: 'Beneficiary account closed - reversal to partner pending',
      riskFlags: ['Customer not credited', 'Funds in suspense'],
      evidence: [
        { label: 'Credit rejection', reference: 'FMNY-RET-44091', status: 'Received', owner: 'Fairmoney API', state: 'watch' },
        { label: 'Suspense ledger hold', reference: 'SUSP-7742', status: 'Open', owner: 'Operations desk', state: 'watch' },
        { label: 'Checker approval', reference: 'REV-44091', status: 'Pending', owner: 'Ops Lead', state: 'watch' },
      ],
      timeline: [
        { label: 'Funds received from partner', owner: 'Hellenic Remit', status: 'done', time: '13:58:40', source: 'Partner instruction', reference: 'HR-330512' },
        { label: 'Credit posted to MFB', owner: 'Fairmoney API', status: 'done', time: '14:02:10', duration: '3m 30s' },
        { label: 'Credit rejected by MFB', owner: 'Fairmoney API', status: 'done', time: '14:08:55', note: 'Account closed - funds returned to suspense' },
        { label: 'Reversal to partner', owner: 'Reversal checker', status: 'current', time: '14:12:00', note: 'Awaiting maker-checker on reversal instruction' },
      ],
    },
    {
      reference: 'CRD-90255',
      contractId: 'CON-UK-NG-01',
      partner: 'Sterling Send (UK)',
      partnerReference: 'SS-7742044',
      originCountry: 'United Kingdom',
      destinationCountry: 'Nigeria',
      beneficiary: 'Tunde Bakare',
      beneficiaryAccount: 'Fidelity 012***7832',
      endpoint: 'Fidelity Bank core (NIP)',
      endpointKind: 'Local bank',
      amount: 'NGN 4,100,000',
      valueAtRisk: 'NGN 4,100,000',
      receivedAt: '14:18:05 UTC',
      creditedAt: 'Pending',
      elapsed: '12m 04s',
      slaDueAt: '14:19:35 UTC',
      slaState: 'degraded',
      creditState: 'recon_break',
      state: 'degraded',
      reversal: false,
      reconState: 'Exception review required',
      evidenceStatus: 'Ledger posting missing',
      railReference: 'NIP-TRF-88421',
      bankPostingReference: 'Not found',
      settlementBatch: 'SET-UK-20260519-044',
      callbackLag: '9m 09s',
      lastCallbackAt: '14:21:00 UTC',
      postingAttempts: 1,
      makerCheckerStatus: 'Evidence review open',
      nextAction: 'Verify NIP session and suspense ledger before resolving',
      owner: 'Settlement Ops',
      blocker: 'Partner says paid, bank ledger has no matching credit',
      riskFlags: ['Potential duplicate-credit risk', 'Partner paid status conflicts with ledger'],
      evidence: [
        { label: 'Partner completed webhook', reference: 'SS-7742044', status: 'Received', owner: 'Sterling Send', state: 'healthy' },
        { label: 'NIP session', reference: 'NIP-TRF-88421', status: 'Needs verification', owner: 'Settlement Ops', state: 'degraded' },
        { label: 'Core ledger posting', reference: 'FBN-LEDGER-SEARCH', status: 'Missing', owner: 'Settlement Ops', state: 'degraded' },
      ],
      timeline: [
        { label: 'Funds received from partner', owner: 'Sterling Send', status: 'done', time: '14:18:05', source: 'Partner instruction', reference: 'SS-7742044' },
        { label: 'Credit instruction sent', owner: 'NIP', status: 'done', time: '14:18:22', duration: '17s' },
        { label: 'Partner reported paid', owner: 'Sterling Send', status: 'done', time: '14:21:00', note: 'Status webhook: COMPLETED' },
        { label: 'Bank ledger match', owner: 'Settlement Ops', status: 'current', time: '14:30:09', note: 'No NIP posting found - reconciliation break opened' },
      ],
    },
    {
      reference: 'CRD-90260',
      contractId: 'CON-UK-NG-03',
      partner: 'Albion Money (UK)',
      partnerReference: 'AM-55120',
      originCountry: 'United Kingdom',
      destinationCountry: 'Nigeria',
      beneficiary: 'Blessing Udo',
      beneficiaryAccount: 'OPay 805***9012',
      endpoint: 'OPay wallet',
      endpointKind: 'Fintech wallet',
      amount: 'NGN 620,000',
      valueAtRisk: 'NGN 620,000',
      receivedAt: '14:31:50 UTC',
      creditedAt: '-',
      elapsed: '11s',
      slaDueAt: '14:32:20 UTC',
      slaState: 'watch',
      creditState: 'received',
      state: 'watch',
      reversal: false,
      reconState: 'Auto-matching',
      evidenceStatus: 'Compliance decision pending',
      railReference: 'OPAY-WLT-93044',
      bankPostingReference: 'Held',
      settlementBatch: 'SET-UK-20260519-045',
      callbackLag: 'Not started',
      lastCallbackAt: '-',
      postingAttempts: 0,
      makerCheckerStatus: 'Compliance maker review',
      nextAction: 'Compliance must clear sanctions match before wallet credit',
      owner: 'Compliance',
      blocker: 'Sanctions screening hold on beneficiary',
      riskFlags: ['Sanctions false-positive review', 'Credit blocked before posting'],
      evidence: [
        { label: 'Partner instruction', reference: 'AM-55120', status: 'Received', owner: 'Albion Money', state: 'healthy' },
        { label: 'Sanctions screening', reference: 'CASE-SANC-90260', status: 'Open', owner: 'Compliance', state: 'watch' },
        { label: 'Wallet credit', reference: 'OPAY-WLT-93044', status: 'Held', owner: 'OPay API', state: 'watch' },
      ],
      timeline: [
        { label: 'Funds received from partner', owner: 'Albion Money', status: 'done', time: '14:31:50', source: 'Partner instruction', reference: 'AM-55120' },
        { label: 'Compliance screening', owner: 'Compliance', status: 'current', time: '14:31:55', note: 'Sanctions name match - manual review' },
        { label: 'Credit to wallet', owner: 'OPay API', status: 'pending', time: '-' },
      ],
    },
    {
      reference: 'CRD-90271',
      contractId: 'CON-UK-NG-01',
      partner: 'Sterling Send (UK)',
      partnerReference: 'SS-7742110',
      originCountry: 'United Kingdom',
      destinationCountry: 'Nigeria',
      beneficiary: 'Ifeanyi Nwankwo',
      beneficiaryAccount: 'NUBAN 044***6620',
      endpoint: 'Paystack transfer',
      endpointKind: 'Payment gateway',
      amount: 'NGN 720,000',
      valueAtRisk: 'NGN 720,000',
      receivedAt: '14:26:42 UTC',
      creditedAt: 'Pending',
      elapsed: '5m 28s',
      slaDueAt: '14:28:12 UTC',
      slaState: 'watch',
      creditState: 'crediting',
      state: 'watch',
      reversal: false,
      reconState: 'Awaiting gateway callback',
      evidenceStatus: 'Gateway final status pending',
      railReference: 'PSTK-TRF-77810',
      bankPostingReference: 'Pending',
      settlementBatch: 'SET-UK-20260519-044',
      callbackLag: '5m 20s',
      lastCallbackAt: '14:26:50 UTC',
      postingAttempts: 1,
      makerCheckerStatus: 'Monitor only',
      nextAction: 'Query Paystack transfer status if callback reaches 7m',
      owner: 'Paystack monitor',
      blocker: 'Paystack debit accepted; transfer callback is overdue',
      riskFlags: ['Gateway status pending', 'Customer notification held'],
      evidence: [
        { label: 'Partner instruction', reference: 'SS-7742110', status: 'Matched', owner: 'Sterling Send', state: 'healthy' },
        { label: 'Gateway transfer', reference: 'PSTK-TRF-77810', status: 'Accepted', owner: 'Paystack Transfer', state: 'watch' },
        { label: 'Final callback', reference: 'PSTK-CB-77810', status: 'Overdue', owner: 'Paystack monitor', state: 'watch' },
      ],
      timeline: [
        { label: 'Funds received from partner', owner: 'Sterling Send', status: 'done', time: '14:26:42', source: 'Partner instruction', reference: 'SS-7742110' },
        { label: 'Paystack transfer created', owner: 'Paystack Transfer', status: 'done', time: '14:26:50', duration: '8s' },
        { label: 'Gateway callback', owner: 'Paystack monitor', status: 'current', time: '14:32:10', note: 'Debit accepted, final transfer status pending' },
        { label: 'Settlement reconciled', owner: 'Settlement Ops', status: 'pending', time: '-' },
      ],
    },
  ],
  inboundSla: [
    { contractId: 'CON-UK-NG-01', partner: 'Sterling Send (UK)', corridor: 'United Kingdom -> Nigeria', creditSla: '90s', p95Credit: '24s', breachRate: '1.6%', agingBreaches: 1, valueAtRisk: 'NGN 4.82M', oldestBreach: '12m 04s', breachReason: 'NIP ledger evidence missing', owner: 'Settlement Ops', recommendedAction: 'Verify NIP session before resolving ledger break', state: 'healthy', trend: '-0.4% vs last week' },
    { contractId: 'CON-GR-NG-02', partner: 'Hellenic Remit (Greece)', corridor: 'Greece -> Nigeria', creditSla: '120s', p95Credit: '4m 02s', breachRate: '5.2%', agingBreaches: 6, valueAtRisk: 'NGN 2.44M', oldestBreach: '8m 12s', breachReason: 'Moniepoint callback lag', owner: 'Provider callback desk', recommendedAction: 'Escalate endpoint callback lag at 10m aging', state: 'degraded', trend: '+2.1% vs last week' },
    { contractId: 'CON-UK-NG-03', partner: 'Albion Money (UK)', corridor: 'United Kingdom -> Nigeria', creditSla: '30s', p95Credit: '14s', breachRate: '1.0%', agingBreaches: 0, valueAtRisk: 'NGN 620K', oldestBreach: '11s', breachReason: 'Compliance hold before wallet credit', owner: 'Compliance', recommendedAction: 'Clear sanctions false-positive before OPay credit', state: 'healthy', trend: 'flat vs last week' },
  ],
  complianceHolds: [
    { reference: 'CRD-90260', partner: 'Albion Money (UK)', type: 'Sanctions', beneficiary: 'Blessing Udo', amount: 'NGN 620,000', age: '11s', dueAt: '14:32:20 UTC', decisionSla: '30s', requiredEvidence: 'Screening disposition and false-positive reason', partnerRfiReference: 'CASE-SANC-90260', owner: 'Compliance', valueAtRisk: 'NGN 620,000', state: 'watch', note: 'Name match against sanctions list - manual review.' },
    { reference: 'CRD-90229', partner: 'Hellenic Remit (Greece)', type: 'KYC', beneficiary: 'Emeka Nwosu', amount: 'NGN 2,300,000', age: '22m', dueAt: '14:15:00 UTC', decisionSla: '10m', requiredEvidence: 'KYC tier upgrade or partner return instruction', partnerRfiReference: 'RFI-HR-90229', owner: 'Compliance', valueAtRisk: 'NGN 2,300,000', state: 'degraded', note: 'Beneficiary KYC tier below threshold for amount.' },
    { reference: 'CRD-90237', partner: 'Sterling Send (UK)', type: 'RFI', beneficiary: 'Funmi Adeyemi', amount: 'NGN 980,000', age: '38m', dueAt: '14:05:00 UTC', decisionSla: '15m', requiredEvidence: 'Source-of-funds response from partner', partnerRfiReference: 'RFI-SS-90237', owner: 'Compliance', valueAtRisk: 'NGN 980,000', state: 'watch', note: 'Request for information sent to partner on source of funds.' },
  ],
  featureSwitches: [
    { key: 'externalDebitRailOps', label: 'Debit and refund rail operations', enabled: false, defaultEnabled: false, reason: 'Advanced exception mode, hidden from primary navigation.' },
    { key: 'walletAndCashPickup', label: 'Wallet and cash pickup endpoints', enabled: false, defaultEnabled: false, reason: 'Account payout stays focused on bank-credit proof.' },
    { key: 'advancedFxCosts', label: 'Advanced FX and cost board', enabled: false, defaultEnabled: false, reason: 'Useful for treasury, not needed to prove final-leg credit.' },
    { key: 'providerCommercialScorecards', label: 'Provider commercial scorecards', enabled: false, defaultEnabled: false, reason: 'Executive/provider management stays behind settings.' },
    { key: 'policySimulator', label: 'Policy simulator and replay', enabled: false, defaultEnabled: false, reason: 'Shadow-routing is advanced configuration.' },
    { key: 'multiBankPortfolio', label: 'Multi-bank portfolio view', enabled: false, defaultEnabled: false, reason: 'Pilot is anchored on Fidelity Bank operations.' },
    { key: 'advancedComplianceCases', label: 'Advanced compliance cases', enabled: false, defaultEnabled: false, reason: 'Only lightweight hold visibility is shown by default.' },
    { key: 'settlementFileImports', label: 'Settlement file imports', enabled: false, defaultEnabled: false, reason: 'Bulk imports belong in low-frequency settings.' },
  ],
  standingAccounts: [
    {
      id: 'SA-FID-GBP-001',
      partner: 'Sterling Send (UK)',
      currency: 'NGN',
      prefundBalance: 'NGN 742.6M',
      availableLimit: 'NGN 1.12B',
      projectedExhaustion: '18h 40m at current flow',
      creditFacility: {
        limit: 'NGN 380M',
        utilized: 'NGN 0',
        available: 'NGN 380M',
        rules: 'Overdraft allowed only for proven partner settlement batches.',
        state: 'healthy',
      },
      state: 'healthy',
    },
    {
      id: 'SA-FID-EUR-002',
      partner: 'Hellenic Remit (Greece)',
      currency: 'NGN',
      prefundBalance: 'NGN 118.4M',
      availableLimit: 'NGN 178.4M',
      projectedExhaustion: '4h 15m at current flow',
      creditFacility: {
        limit: 'NGN 60M',
        utilized: 'NGN 22M',
        available: 'NGN 38M',
        rules: 'Credit line pauses after two unresolved SLA breaches.',
        state: 'watch',
      },
      state: 'watch',
    },
  ],
  slaPolicies: [
    {
      id: 'SLA-NG-ACCT-90',
      name: 'Nigeria account credit SLA',
      duration: '90s',
      cooldownWindow: '15m',
      lateSuccessWindow: '30m',
      evidenceRequired: ['Rail/session response', 'Core ledger posting', 'Provider callback'],
      state: 'watch',
    },
    {
      id: 'SLA-NG-INTRA-30',
      name: 'Fidelity intra-bank credit SLA',
      duration: '30s',
      cooldownWindow: '5m',
      lateSuccessWindow: '10m',
      evidenceRequired: ['Core ledger posting', 'Audit event'],
      state: 'healthy',
    },
  ],
  backoffPolicies: [
    {
      id: 'BCK-NIP-90',
      route: 'NIP final leg',
      slaPolicyId: 'SLA-NG-ACCT-90',
      maxRequeryAttempts: 4,
      schedule: ['T+30s', 'T+2m', 'T+5m', 'T+15m'],
      rerouteAfterAcceptance: false,
      state: 'watch',
    },
    {
      id: 'BCK-INTRA-30',
      route: 'Fidelity core',
      slaPolicyId: 'SLA-NG-INTRA-30',
      maxRequeryAttempts: 3,
      schedule: ['T+10s', 'T+45s', 'T+3m'],
      rerouteAfterAcceptance: false,
      state: 'healthy',
    },
  ],
  inboundContracts: [
    {
      id: 'CON-UK-NG-01',
      partner: 'Sterling Send (UK)',
      corridor: 'United Kingdom -> Nigeria',
      standingAccountId: 'SA-FID-GBP-001',
      slaPolicyId: 'SLA-NG-ACCT-90',
      permittedRails: ['Fidelity core', 'NIP', 'Interswitch'],
      permittedDestinationBanks: ['Fidelity Bank', 'Access Bank', 'UBA', 'GTBank'],
      settlementModel: 'Prefunded standing account',
      owner: 'Operations desk',
      state: 'watch',
    },
    {
      id: 'CON-GR-NG-02',
      partner: 'Hellenic Remit (Greece)',
      corridor: 'Greece -> Nigeria',
      standingAccountId: 'SA-FID-EUR-002',
      slaPolicyId: 'SLA-NG-ACCT-90',
      permittedRails: ['NIP', 'Moniepoint'],
      permittedDestinationBanks: ['Access Bank', 'Moniepoint MFB', 'Fairmoney MFB'],
      settlementModel: 'Prefund plus limited credit line',
      owner: 'Route Desk',
      state: 'degraded',
    },
  ],
  incomingInstructions: [
    {
      reference: 'INF-10001',
      partnerReference: 'BX-ENG-77102',
      contractId: 'CON-UK-NG-01',
      origin: 'Bank X in England',
      destination: 'Fidelity Bank Nigeria',
      amount: 'NGN 2,400,000',
      beneficiary: 'Adaeze Chukwu',
      beneficiaryAccount: 'Fidelity 003***9011',
      destinationBank: 'Fidelity Bank',
      settlementBatch: 'SET-UK-20260519-044',
      receivedAt: '14:28:01 UTC',
      slaDeadline: '14:28:31 UTC',
      currentState: 'credited',
      outcomeConfidence: 'proven_credited',
      route: 'Fidelity core',
      owner: 'Route engine',
      safeAction: 'No action. Ledger posting and audit evidence are matched.',
      valueAtRisk: 'NGN 0',
      state: 'healthy',
    },
    {
      reference: 'INF-10002',
      partnerReference: 'BX-ENG-77118',
      contractId: 'CON-UK-NG-01',
      origin: 'Bank X in England',
      destination: 'Access Bank Nigeria',
      amount: 'NGN 4,100,000',
      beneficiary: 'Tunde Bakare',
      beneficiaryAccount: 'Access 012***7832',
      destinationBank: 'Access Bank',
      settlementBatch: 'SET-UK-20260519-044',
      receivedAt: '14:18:05 UTC',
      slaDeadline: '14:19:35 UTC',
      currentState: 'manual_remediation',
      outcomeConfidence: 'unsafe_failed',
      route: 'NIP final leg',
      owner: 'Settlement Ops',
      safeAction: 'Verify NIP session and suspense ledger before closure. Do not reroute.',
      valueAtRisk: 'NGN 4,100,000',
      state: 'degraded',
    },
    {
      reference: 'INF-10003',
      partnerReference: 'HR-330418',
      contractId: 'CON-GR-NG-02',
      origin: 'Hellenic Remit (Greece)',
      destination: 'Moniepoint MFB Nigeria',
      amount: 'NGN 880,000',
      beneficiary: 'Amina Yusuf',
      beneficiaryAccount: 'Moniepoint 604***1180',
      destinationBank: 'Moniepoint MFB',
      settlementBatch: 'SET-GR-20260519-019',
      receivedAt: '14:24:11 UTC',
      slaDeadline: '14:26:11 UTC',
      currentState: 'requerying',
      outcomeConfidence: 'uncertain',
      route: 'Moniepoint final leg',
      owner: 'Rail requery desk',
      safeAction: 'Run scheduled requery, then request provider evidence if callback remains missing.',
      valueAtRisk: 'NGN 880,000',
      state: 'watch',
    },
    {
      reference: 'INF-10005',
      partnerReference: 'BX-ENG-77132',
      contractId: 'CON-UK-NG-01',
      origin: 'Bank X in England',
      destination: 'UBA Nigeria',
      amount: 'NGN 540,000',
      beneficiary: 'Ngozi Eze',
      beneficiaryAccount: 'UBA 033***7621',
      destinationBank: 'UBA',
      settlementBatch: 'SET-UK-20260519-044',
      receivedAt: '14:31:03 UTC',
      slaDeadline: '14:32:33 UTC',
      currentState: 'cooldown',
      outcomeConfidence: 'probably_pending',
      route: 'NIP final leg',
      owner: 'Rail requery desk',
      safeAction: 'Freeze duplicate action until the first automatic requery window opens.',
      valueAtRisk: 'NGN 540,000',
      state: 'watch',
    },
    {
      reference: 'INF-10004',
      partnerReference: 'ISW-55092',
      contractId: 'CON-UK-NG-01',
      origin: 'Bank X in England',
      destination: 'GTBank Nigeria',
      amount: 'NGN 1,220,000',
      beneficiary: 'Kelechi Okoye',
      beneficiaryAccount: 'GTBank 014***3320',
      destinationBank: 'GTBank',
      settlementBatch: 'SET-UK-20260519-046',
      receivedAt: '14:06:44 UTC',
      slaDeadline: '14:08:14 UTC',
      currentState: 'reversal_pending',
      outcomeConfidence: 'safe_failed',
      route: 'Interswitch final leg',
      owner: 'Reversal checker',
      safeAction: 'Approve reversal after maker-checker confirms no credit occurred.',
      valueAtRisk: 'NGN 1,220,000',
      state: 'watch',
    },
  ],
  finalLegAttempts: [
    {
      id: 'ATT-INF-10001-01',
      instructionReference: 'INF-10001',
      route: 'Fidelity core',
      rail: 'Intra-bank',
      destinationBank: 'Fidelity Bank',
      submittedAt: '14:28:05 UTC',
      acceptedAt: '14:28:06 UTC',
      creditedAt: '14:28:12 UTC',
      p95CreditTime: '12s',
      timeoutRate: '0.02%',
      lateSuccessRisk: 'Low',
      state: 'credited',
      health: 'healthy',
      decisionReason: 'Beneficiary is Fidelity; intra-bank route is safest and fastest.',
    },
    {
      id: 'ATT-INF-10002-01',
      instructionReference: 'INF-10002',
      route: 'NIP final leg',
      rail: 'NIP',
      destinationBank: 'Access Bank',
      submittedAt: '14:18:22 UTC',
      acceptedAt: '14:18:23 UTC',
      creditedAt: 'Pending',
      p95CreditTime: '4m 18s',
      timeoutRate: '8.7%',
      lateSuccessRisk: 'High',
      state: 'manual_remediation',
      health: 'degraded',
      decisionReason: 'NIP was eligible, but partner paid status conflicts with bank ledger.',
    },
    {
      id: 'ATT-INF-10003-01',
      instructionReference: 'INF-10003',
      route: 'Moniepoint final leg',
      rail: 'Moniepoint',
      destinationBank: 'Moniepoint MFB',
      submittedAt: '14:24:40 UTC',
      acceptedAt: '14:24:42 UTC',
      creditedAt: 'Unproven',
      p95CreditTime: '4m 02s',
      timeoutRate: '5.2%',
      lateSuccessRisk: 'Medium',
      state: 'requerying',
      health: 'watch',
      decisionReason: 'Endpoint allowed by contract; callback evidence is overdue.',
    },
    {
      id: 'ATT-INF-10005-01',
      instructionReference: 'INF-10005',
      route: 'NIP final leg',
      rail: 'NIP',
      destinationBank: 'UBA',
      submittedAt: '14:31:18 UTC',
      acceptedAt: '14:31:19 UTC',
      creditedAt: 'Cooldown',
      p95CreditTime: '4m 18s',
      timeoutRate: '8.7%',
      lateSuccessRisk: 'Medium',
      state: 'cooldown',
      health: 'watch',
      decisionReason: 'NIP accepted the request; late success remains possible before first requery.',
    },
    {
      id: 'ATT-INF-10004-01',
      instructionReference: 'INF-10004',
      route: 'Interswitch final leg',
      rail: 'Interswitch',
      destinationBank: 'GTBank',
      submittedAt: '14:06:59 UTC',
      acceptedAt: '14:07:00 UTC',
      creditedAt: 'Failed safe',
      p95CreditTime: '52s',
      timeoutRate: '0.9%',
      lateSuccessRisk: 'Low',
      state: 'reversal_pending',
      health: 'watch',
      decisionReason: 'Rail returned final failure with no beneficiary credit evidence.',
    },
  ],
  requeryAttempts: [
    { id: 'RQ-INF-10002-01', instructionReference: 'INF-10002', attemptNumber: 1, dueAt: '14:20:05 UTC', completedAt: '14:20:09 UTC', method: 'NIP session lookup', result: 'Session not found in core ledger.', trigger: 'automatic', state: 'degraded' },
    { id: 'RQ-INF-10002-02', instructionReference: 'INF-10002', attemptNumber: 2, dueAt: '14:23:05 UTC', completedAt: '14:23:12 UTC', method: 'Partner callback check', result: 'Partner still reports paid.', trigger: 'automatic', state: 'watch' },
    { id: 'RQ-INF-10002-03', instructionReference: 'INF-10002', attemptNumber: 3, dueAt: '14:28:05 UTC', completedAt: '14:28:19 UTC', method: 'Ledger and suspense search', result: 'No matching posting found.', trigger: 'automatic', state: 'degraded' },
    { id: 'RQ-INF-10003-01', instructionReference: 'INF-10003', attemptNumber: 1, dueAt: '14:26:41 UTC', completedAt: '14:26:46 UTC', method: 'Moniepoint status API', result: 'Accepted, final callback pending.', trigger: 'automatic', state: 'watch' },
    { id: 'RQ-INF-10003-02', instructionReference: 'INF-10003', attemptNumber: 2, dueAt: '14:29:41 UTC', completedAt: '-', method: 'Provider callback replay', result: 'Due now', trigger: 'automatic', state: 'watch' },
  ],
  outcomeEvidence: [
    { instructionReference: 'INF-10001', type: 'ledger_posting', label: 'Core ledger posting', reference: 'FID-LED-22091', status: 'Matched', owner: 'Fidelity core', state: 'healthy' },
    { instructionReference: 'INF-10001', type: 'audit_event', label: 'Credit audit event', reference: 'AUD-INF-10001', status: 'Stored', owner: 'Audit trail', state: 'healthy' },
    { instructionReference: 'INF-10002', type: 'partner_callback', label: 'Partner completed webhook', reference: 'BX-ENG-77118', status: 'Received', owner: 'Bank X', state: 'healthy' },
    { instructionReference: 'INF-10002', type: 'rail_session', label: 'NIP session', reference: 'NIP-TRF-88421', status: 'Needs verification', owner: 'Settlement Ops', state: 'degraded' },
    { instructionReference: 'INF-10002', type: 'ledger_posting', label: 'Core ledger posting', reference: 'FBN-LEDGER-SEARCH', status: 'Missing', owner: 'Settlement Ops', state: 'degraded' },
    { instructionReference: 'INF-10003', type: 'partner_callback', label: 'Final credit callback', reference: 'MPT-TRF-55381', status: 'Overdue', owner: 'Provider callback desk', state: 'watch' },
    { instructionReference: 'INF-10005', type: 'rail_session', label: 'NIP accepted session', reference: 'NIP-TRF-88437', status: 'Cooldown before first requery', owner: 'Rail requery desk', state: 'watch' },
    { instructionReference: 'INF-10004', type: 'rail_session', label: 'Interswitch final status', reference: 'ISW-55092', status: 'Failed safe', owner: 'Interswitch', state: 'healthy' },
    { instructionReference: 'INF-10004', type: 'operator_note', label: 'Reversal maker note', reference: 'REV-ISW-55092', status: 'Pending checker', owner: 'Reversal checker', state: 'watch' },
  ],
  remediationCases: [
    {
      id: 'CASE-INF-10002',
      instructionReference: 'INF-10002',
      apiReference: 'CRD-90288',
      queue: 'exhausted',
      route: 'NIP final leg',
      provider: 'NIP',
      requeryMethod: 'NIP session lookup + core ledger search',
      automaticAttempts: 3,
      maxAutomaticAttempts: 3,
      nextRequeryAt: 'Manual only',
      automationStatus: 'exhausted',
      title: 'Partner says paid, bank ledger missing',
      theory: 'Possible late-success or missing ledger evidence. Unsafe to fail or reroute.',
      valueAtRisk: 'NGN 4,100,000',
      age: '12m 04s',
      duplicateRisk: 'High',
      evidenceGap: 'Verified NIP session and suspense ledger evidence',
      nextAction: 'Attach NIP session evidence before closure. Do not reroute.',
      owner: 'Settlement Ops',
      makerChecker: 'Maker evidence required',
      makerCheckerState: 'maker_required',
      safeClosure: 'Manual completion needs ledger/session evidence and checker approval because duplicate-credit risk remains high.',
      state: 'degraded',
    },
    {
      id: 'CASE-INF-10003',
      instructionReference: 'INF-10003',
      apiReference: 'CRD-90231',
      queue: 'requerying',
      route: 'Moniepoint final leg',
      provider: 'Moniepoint',
      requeryMethod: 'Moniepoint transfer status API',
      automaticAttempts: 2,
      maxAutomaticAttempts: 4,
      nextRequeryAt: '14:34:41 UTC',
      automationStatus: 'running',
      title: 'Moniepoint callback missing but rail accepted',
      theory: 'Credit may still complete late; automatic requery remains active.',
      valueAtRisk: 'NGN 880,000',
      age: '8m 12s',
      duplicateRisk: 'Medium',
      evidenceGap: 'Final callback or ledger posting',
      nextAction: 'Run provider callback replay.',
      owner: 'Provider callback desk',
      makerChecker: 'Automation active',
      makerCheckerState: 'not_required',
      safeClosure: 'Do not close until Moniepoint callback or ledger posting proves beneficiary credit.',
      state: 'watch',
    },
    {
      id: 'CASE-INF-10004',
      instructionReference: 'INF-10004',
      apiReference: 'CRD-90244',
      queue: 'reversal',
      route: 'Interswitch final leg',
      provider: 'Interswitch',
      requeryMethod: 'Interswitch final status API',
      automaticAttempts: 1,
      maxAutomaticAttempts: 2,
      nextRequeryAt: 'Manual confirmation before reversal',
      automationStatus: 'manual_only',
      title: 'Interswitch failed-safe reversal pending',
      theory: 'Rail confirms no credit occurred; reversal can proceed after checker approval.',
      valueAtRisk: 'NGN 1,220,000',
      age: '24m',
      duplicateRisk: 'Low',
      evidenceGap: 'Checker approval',
      nextAction: 'Approve reversal to partner.',
      owner: 'Reversal checker',
      makerChecker: 'Checker approval pending',
      makerCheckerState: 'checker_pending',
      safeClosure: 'Safe reversal requires maker-checker approval and final failed-safe rail evidence.',
      state: 'watch',
    },
  ],
  routePenalties: [
    { route: 'Fidelity core', rail: 'Intra-bank', destinationBank: 'Fidelity Bank', p95CreditTime: '12s', timeoutRate: '0.02%', lateSuccessRate: '0.00%', openCases: 0, penaltyScore: 2, penaltyReason: 'No active penalty.', trafficSplit: '100% Fidelity beneficiaries', fallbackOrder: 'No fallback needed', state: 'healthy' },
    { route: 'NIP final leg', rail: 'NIP', destinationBank: 'External banks', p95CreditTime: '4m 18s', timeoutRate: '8.7%', lateSuccessRate: '2.4%', openCases: 4, penaltyScore: 38, penaltyReason: 'Timeouts and ledger/provider status conflict.', trafficSplit: '42% of eligible external traffic', fallbackOrder: 'Moniepoint, Interswitch', state: 'degraded' },
    { route: 'Moniepoint final leg', rail: 'Moniepoint', destinationBank: 'MFBs and wallets', p95CreditTime: '41s', timeoutRate: '0.3%', lateSuccessRate: '0.0%', openCases: 0, penaltyScore: 4, penaltyReason: 'Fastest P95 and no open repair cases in this window.', trafficSplit: '36% of eligible external traffic', fallbackOrder: 'Interswitch, Paystack, NIP', state: 'healthy' },
    { route: 'Interswitch final leg', rail: 'Interswitch', destinationBank: 'External banks', p95CreditTime: '52s', timeoutRate: '0.9%', lateSuccessRate: '0.1%', openCases: 1, penaltyScore: 12, penaltyReason: 'One failed-safe reversal waiting maker-checker.', trafficSplit: '12% of eligible external traffic', fallbackOrder: 'Moniepoint, Paystack, NIP', state: 'watch' },
    { route: 'Paystack final leg', rail: 'Paystack', destinationBank: 'NUBAN and supported wallets', p95CreditTime: '1m 26s', timeoutRate: '2.1%', lateSuccessRate: '0.4%', openCases: 2, penaltyScore: 20, penaltyReason: 'Transfer callback lag is above the Moniepoint and Interswitch windows.', trafficSplit: '10% of eligible external traffic', fallbackOrder: 'Moniepoint, Interswitch, NIP', state: 'watch' },
  ],
  routeDecisions: [
    {
      instructionReference: 'INF-10002',
      sourceTable: 'route_decisions',
      policyVersion: 'policy-ng-acct-2026.06.03',
      selectedRoute: 'NIP final leg',
      selectedRail: 'NIP',
      score: 71.4,
      decidedAt: '14:18:20 UTC',
      decisionReason: 'NIP was eligible at submission time, but later ledger evidence diverged from partner completed status.',
      scoreInputs: [
        { label: 'Contract allowed', value: 'Yes', state: 'healthy' },
        { label: 'P95 credit', value: '4m 18s', state: 'degraded' },
        { label: 'Timeout', value: '8.7%', state: 'degraded' },
        { label: 'Fallback', value: 'Moniepoint, Interswitch', state: 'watch' },
      ],
      rejectedRoutes: [
        { provider: 'Fidelity core', route: 'Intra-bank', reason: 'Beneficiary bank is Access Bank, not Fidelity.' },
        { provider: 'Moniepoint', route: 'Moniepoint final leg', reason: 'Destination bank not covered by this endpoint.' },
        { provider: 'Interswitch', route: 'Interswitch final leg', reason: 'Lower policy score at decision time.' },
      ],
    },
    {
      instructionReference: 'INF-10003',
      sourceTable: 'route_decisions',
      policyVersion: 'policy-ng-acct-2026.06.03',
      selectedRoute: 'Moniepoint final leg',
      selectedRail: 'Moniepoint',
      score: 76.2,
      decidedAt: '14:24:38 UTC',
      decisionReason: 'Contract permits Moniepoint MFB payout; final callback is now overdue.',
      scoreInputs: [
        { label: 'Endpoint coverage', value: 'Moniepoint MFB', state: 'healthy' },
        { label: 'Callback lag', value: 'Overdue', state: 'watch' },
        { label: 'Manual burden', value: 'Medium', state: 'watch' },
      ],
      rejectedRoutes: [
        { provider: 'NIP', route: 'NIP final leg', reason: 'MFB endpoint covered directly by Moniepoint route.' },
        { provider: 'Interswitch', route: 'Interswitch final leg', reason: 'Fallback only for this contract.' },
      ],
    },
    {
      instructionReference: 'INF-10004',
      sourceTable: 'route_decisions',
      policyVersion: 'policy-ng-acct-2026.06.03',
      selectedRoute: 'Interswitch final leg',
      selectedRail: 'Interswitch',
      score: 82.8,
      decidedAt: '14:06:57 UTC',
      decisionReason: 'Interswitch was healthy and contract-permitted for GTBank final leg.',
      scoreInputs: [
        { label: 'Final failure proof', value: 'Available', state: 'recovery' },
        { label: 'P95 credit', value: '52s', state: 'healthy' },
        { label: 'Timeout', value: '0.9%', state: 'healthy' },
      ],
      rejectedRoutes: [
        { provider: 'NIP', route: 'NIP final leg', reason: 'Higher timeout pressure in this window.' },
        { provider: 'Moniepoint', route: 'Moniepoint final leg', reason: 'Destination bank unsupported.' },
      ],
    },
  ],
  evidenceRequirements: [
    { id: 'REQ-INF-10002-CB', instructionReference: 'INF-10002', slaPolicyId: 'SLA-NG-ACCT-90', sourceTable: 'outcome_evidence', label: 'Partner completed callback', evidenceType: 'partner_callback', required: true, capturedReference: 'BX-ENG-77118', status: 'Captured', state: 'healthy' },
    { id: 'REQ-INF-10002-RAIL', instructionReference: 'INF-10002', slaPolicyId: 'SLA-NG-ACCT-90', sourceTable: 'outcome_evidence', label: 'Rail/session evidence', evidenceType: 'rail_session', required: true, capturedReference: 'NIP-TRF-88421', status: 'Needs verification', state: 'degraded' },
    { id: 'REQ-INF-10002-LEDGER', instructionReference: 'INF-10002', slaPolicyId: 'SLA-NG-ACCT-90', sourceTable: 'outcome_evidence', label: 'Core ledger posting', evidenceType: 'ledger_posting', required: true, capturedReference: 'FBN-LEDGER-SEARCH', status: 'Missing', state: 'degraded' },
    { id: 'REQ-INF-10003-CB', instructionReference: 'INF-10003', slaPolicyId: 'SLA-NG-ACCT-90', sourceTable: 'outcome_evidence', label: 'Final callback', evidenceType: 'partner_callback', required: true, capturedReference: 'MPT-TRF-55381', status: 'Overdue', state: 'watch' },
    { id: 'REQ-INF-10004-RAIL', instructionReference: 'INF-10004', slaPolicyId: 'SLA-NG-ACCT-90', sourceTable: 'outcome_evidence', label: 'Failed-safe rail status', evidenceType: 'rail_session', required: true, capturedReference: 'ISW-55092', status: 'Captured', state: 'healthy' },
    { id: 'REQ-INF-10004-NOTE', instructionReference: 'INF-10004', slaPolicyId: 'SLA-NG-ACCT-90', sourceTable: 'outcome_evidence', label: 'Checker approval note', evidenceType: 'operator_note', required: true, capturedReference: 'REV-ISW-55092', status: 'Pending checker', state: 'watch' },
  ],
  reconciliationMatches: [
    { instructionReference: 'INF-10002', sourceTable: 'reconciliation_matches', settlementBatch: 'SET-UK-20260519-044', providerFileReference: 'BX-ENG-77118', bankLedgerReference: 'FBN-LEDGER-SEARCH', matchState: 'Break open', mismatchReason: 'Provider file says paid but core ledger posting is missing.', resolvedAt: 'Open', state: 'degraded' },
    { instructionReference: 'INF-10003', sourceTable: 'reconciliation_matches', settlementBatch: 'SET-GR-20260519-019', providerFileReference: 'MPT-TRF-55381', bankLedgerReference: 'Pending', matchState: 'Awaiting callback', mismatchReason: 'Rail accepted but final callback has not landed.', resolvedAt: 'Open', state: 'watch' },
    { instructionReference: 'INF-10004', sourceTable: 'reconciliation_matches', settlementBatch: 'SET-UK-20260519-046', providerFileReference: 'ISW-55092', bankLedgerReference: 'No credit posted', matchState: 'Failed-safe', mismatchReason: 'No beneficiary credit occurred; reversal approval pending.', resolvedAt: 'Pending checker', state: 'watch' },
  ],
  routeHealthWindows: [
    { route: 'NIP final leg', sourceTable: 'route_health_windows', rail: 'NIP', window: '14:00-14:15', submittedCount: 182, creditedCount: 169, failedCount: 3, timeoutCount: 14, openCases: 3, p95CreditTime: '4m 42s', lateSuccessCount: 5, state: 'degraded' },
    { route: 'NIP final leg', sourceTable: 'route_health_windows', rail: 'NIP', window: '14:15-14:30', submittedCount: 164, creditedCount: 150, failedCount: 4, timeoutCount: 16, openCases: 4, p95CreditTime: '4m 18s', lateSuccessCount: 4, state: 'degraded' },
    { route: 'Moniepoint final leg', sourceTable: 'route_health_windows', rail: 'Moniepoint', window: '14:00-14:15', submittedCount: 124, creditedCount: 124, failedCount: 0, timeoutCount: 0, openCases: 0, p95CreditTime: '43s', lateSuccessCount: 0, state: 'healthy' },
    { route: 'Moniepoint final leg', sourceTable: 'route_health_windows', rail: 'Moniepoint', window: '14:15-14:30', submittedCount: 136, creditedCount: 135, failedCount: 0, timeoutCount: 1, openCases: 0, p95CreditTime: '41s', lateSuccessCount: 0, state: 'healthy' },
    { route: 'Interswitch final leg', sourceTable: 'route_health_windows', rail: 'Interswitch', window: '14:00-14:15', submittedCount: 48, creditedCount: 47, failedCount: 1, timeoutCount: 0, openCases: 1, p95CreditTime: '52s', lateSuccessCount: 0, state: 'watch' },
    { route: 'Paystack final leg', sourceTable: 'route_health_windows', rail: 'Paystack', window: '14:15-14:30', submittedCount: 72, creditedCount: 69, failedCount: 1, timeoutCount: 2, openCases: 2, p95CreditTime: '1m 26s', lateSuccessCount: 1, state: 'watch' },
  ],
  integrationHealth: [
    { id: 'api-switching-core', sourceTable: 'api_health_windows', serviceName: 'Switching API', endpoint: '/v1/transfers', provider: 'INSWITCH', successRate: '99.98%', timeoutRate: '0.02%', p95Latency: '142ms', polling: '15s polling', callbackStatus: 'Current', lastSuccessAt: '14:32:18 UTC', nextAction: 'No action. Telemetry is current.', state: 'healthy' },
    { id: 'provider-nip-status', sourceTable: 'api_health_windows', serviceName: 'NIP status lookup', endpoint: '/nip/session/status', provider: 'NIP', successRate: '91.3%', timeoutRate: '8.7%', p95Latency: '2.8s', polling: '15s polling', callbackStatus: 'Lagging', lastSuccessAt: '14:31:42 UTC', nextAction: 'Keep NIP repair cases in evidence review.', state: 'degraded' },
    { id: 'provider-moniepoint-callback', sourceTable: 'api_health_windows', serviceName: 'Moniepoint callback listener', endpoint: '/callbacks/moniepoint', provider: 'Moniepoint', successRate: '99.7%', timeoutRate: '0.3%', p95Latency: '410ms', polling: 'Replay every 3m', callbackStatus: 'Current', lastSuccessAt: '14:32:16 UTC', nextAction: 'Prefer Moniepoint for eligible new local payouts.', state: 'healthy' },
    { id: 'provider-interswitch-status', sourceTable: 'api_health_windows', serviceName: 'Interswitch final status', endpoint: '/interswitch/transfers/status', provider: 'Interswitch', successRate: '99.1%', timeoutRate: '0.9%', p95Latency: '620ms', polling: '30s polling', callbackStatus: 'Current', lastSuccessAt: '14:31:59 UTC', nextAction: 'Checker can approve failed-safe reversal with evidence.', state: 'healthy' },
    { id: 'provider-paystack-status', sourceTable: 'api_health_windows', serviceName: 'Paystack transfer status', endpoint: '/paystack/transfer/status', provider: 'Paystack', successRate: '97.9%', timeoutRate: '2.1%', p95Latency: '1.2s', polling: '30s polling', callbackStatus: 'Lagging', lastSuccessAt: '14:30:58 UTC', nextAction: 'Keep Paystack behind Moniepoint until callback lag clears.', state: 'watch' },
  ],
  caseActionSteps: [
    { action: 'attach_evidence', label: 'Attach evidence', queues: ['cooldown', 'requerying', 'exhausted', 'recon_break', 'completed_outside_platform', 'reversal'], duplicateRisk: 'Any', requiresEvidence: true, resultingState: 'Evidence updated', safetyChecklist: ['Evidence reference is specific', 'Reason names source checked', 'No closure action is taken automatically'] },
    { action: 'manual_requery', label: 'Manual requery', queues: ['requerying', 'exhausted'], duplicateRisk: 'Any', requiresEvidence: true, resultingState: 'Requery running', safetyChecklist: ['Automatic attempts reviewed', 'Provider/rail method selected', 'No duplicate credit action is triggered'] },
    { action: 'mark_completed_outside_platform', label: 'Mark completed outside platform', queues: ['exhausted', 'recon_break'], duplicateRisk: 'Low', requiresEvidence: true, resultingState: 'Checker pending', safetyChecklist: ['Ledger or session proof shows customer value delivered', 'Settlement batch is linked', 'Checker approval will be required'] },
    { action: 'approve_reversal', label: 'Approve reversal', queues: ['reversal'], duplicateRisk: 'Low', requiresEvidence: true, resultingState: 'Reversal approved', safetyChecklist: ['Rail confirms no credit occurred', 'Maker note is present', 'Checker approval is captured'] },
  ],
})

export const getDashboardMock = (scenario: UiScenario = 'degraded'): DashboardMock => {
  const dashboard = baseDashboard()
  dashboard.scenario = scenario === 'degraded' ? 'degraded-ria' : scenario

  if (scenario === 'healthy') {
    dashboard.summary.globalHealth = '98.7%'
    dashboard.summary.p95CreditTime = '1m 8s'
    dashboard.summary.stuckTransactions = 12
    dashboard.summary.activeIncidents = 0
    dashboard.summary.atRiskValue = '$180K'
    dashboard.summary.topRisk = 'No corridor outside policy'
    dashboard.summary.safeAction = 'Keep current routing policy active.'
    dashboard.summary.metrics = [
      { label: 'Routes healthy', value: '98.7%', detail: '15 min measured window', trend: '+1.4%', state: 'healthy' },
      { label: 'At-risk value', value: '$180K', detail: '12 transfers pending review', trend: '-$2.5M', state: 'healthy' },
      { label: 'P95 credit time', value: '1m 8s', detail: 'target 90s account payout', trend: '-3m 10s', state: 'healthy' },
      { label: 'Shift candidate', value: '0%', detail: 'no shift needed', trend: 'inside policy', state: 'healthy' },
    ]
    dashboard.recommendation = {
      ...dashboard.recommendation,
      title: 'No route action needed.',
      trigger: 'All monitored routes are inside the current operating policy.',
      affectedTraffic: '0 transfers',
      affectedValue: '$0',
      currentRoute: 'Ria -> NIP',
      suggestedRoute: 'Keep current allocation',
      nextAction: 'Keep monitoring',
      evidence: 'Success and latency are inside SLA.',
      state: 'healthy',
    }
    dashboard.incidents = []
    dashboard.reconciliation = dashboard.reconciliation.slice(0, 1).map((item) => ({
      ...item,
      age: '8m',
      reason: 'Provider file awaiting scheduled refresh',
      state: 'healthy',
    }))
    dashboard.corridors = dashboard.corridors.map((corridor) => ({
      ...corridor,
      state: corridor.state === 'healthy' ? 'healthy' : 'watch',
      score: Math.max(corridor.score, 91),
      risk: 'Inside policy',
      recommendation: 'Monitor',
      status: 'Healthy',
    }))
    dashboard.providerScores = dashboard.providerScores.map((provider) => ({
      ...provider,
      successRate: provider.provider === 'Ria' ? '97.2%' : provider.successRate,
      p95: provider.provider === 'Ria' ? '1m 6s' : provider.p95,
      state: provider.state === 'degraded' ? 'watch' : provider.state,
      settlementExceptions: provider.provider === 'Ria' ? 2 : provider.settlementExceptions,
    }))
    dashboard.visuals.hourHealth = dashboard.visuals.hourHealth.map((point) => ({ ...point, state: 'healthy' }))
  }

  if (scenario === 'traffic-shift') {
    dashboard.summary.globalHealth = '91.4%'
    dashboard.summary.p95CreditTime = '2m 12s'
    dashboard.summary.stuckTransactions = 71
    dashboard.summary.activeIncidents = 1
    dashboard.summary.atRiskValue = '$940K'
    dashboard.summary.topRisk = 'Europe to Nigeria is recovering after a traffic shift'
    dashboard.summary.safeAction = 'Review a staged increase from 25% to 50% on Thunes.'
    dashboard.recommendation = {
      ...dashboard.recommendation,
      title: 'Traffic shift is reducing failed credits.',
      trigger: 'Ria callback lag is down, but destination credit tail latency is still above target.',
      affectedTraffic: '25% shifted',
      affectedValue: '$940K monitored',
      currentRoute: 'Ria -> NIP',
      suggestedRoute: 'Thunes -> NIP',
      nextAction: 'Hold 25% split for one more window, then test 50%.',
      evidence: 'Projected 312 failures avoided in the current window.',
      state: 'recovery',
    }
    dashboard.corridors = dashboard.corridors.map((corridor) =>
      corridor.corridor.includes('European Union') || corridor.corridor.startsWith('EU')
        ? { ...corridor, state: 'recovery', selectedRoute: 'Thunes -> NIP', score: 86, split: '75% Ria / 25% Thunes', recommendation: 'Hold recovery split', risk: 'Ria callbacks improving', status: 'Recovery testing', owner: 'Route Ops' }
        : corridor,
    )
    dashboard.auditEvents = [
      { time: '14:28:14', actor: 'Ops lead', action: 'Held recovery split', object: 'Europe to Nigeria 25%', reason: 'P95 improving after shift', state: 'recovery' },
      ...dashboard.auditEvents,
    ]
  }

  if (scenario === 'pilot-report') {
    dashboard.summary.globalHealth = '96.8%'
    dashboard.summary.valueToday = '$118.7M'
    dashboard.summary.transactionsToday = '286,420'
    dashboard.summary.p95CreditTime = '2m 1s'
    dashboard.summary.stuckTransactions = 910
    dashboard.summary.activeIncidents = 1
    dashboard.summary.atRiskValue = '$1.2M'
    dashboard.summary.topRisk = 'Ria latency improved after staged shifts'
    dashboard.summary.safeAction = 'Export the operating evidence for bank review.'
    dashboard.dateRange.label = '30-day review'
    dashboard.recommendation = {
      ...dashboard.recommendation,
      title: 'Operating evidence is ready for review.',
      trigger: 'Routing changes reduced avoidable failures and improved SLA completion.',
      affectedTraffic: '286,420 transfers',
      affectedValue: '$118.7M processed',
      currentRoute: 'Mixed provider allocation',
      suggestedRoute: 'Policy v2026.05.20.14.30',
      nextAction: 'Review provider scorecards and export the decision log.',
      evidence: '1,184 failures avoided across the review window.',
      state: 'healthy',
    }
    dashboard.incidents = dashboard.incidents.slice(0, 1).map((incident) => ({
      ...incident,
      title: 'Ria callback incident closed with recovery monitoring',
      status: 'Resolved - monitoring',
      severity: 'recovery',
    }))
  }

  if (scenario === 'loading') {
    dashboard.viewState = 'loading'
  }

  if (scenario === 'api-failure') {
    dashboard.viewState = 'error'
    dashboard.summary.connection.freshness = 'unavailable'
    dashboard.summary.connection.mode = 'static'
    dashboard.summary.connection.nextPollIn = 'last verified state'
  }

  if (scenario === 'permission-denied') {
    dashboard.viewState = 'permission-denied'
    dashboard.auditEvents = []
  }

  if (scenario === 'stale-fx') {
    dashboard.viewState = 'stale'
    dashboard.summary.connection.freshness = 'stale'
    dashboard.fxCostBoard.routes = dashboard.fxCostBoard.routes.map((route) =>
      route.provider === 'Remitly' ? { ...route, state: 'stale' as HealthState, note: 'Rate is stale.' } : route,
    )
  }

  if (scenario === 'empty') {
    dashboard.viewState = 'empty'
    dashboard.incidents = []
    dashboard.reconciliation = []
    dashboard.transactions = []
    dashboard.auditEvents = []
    dashboard.creditLegs = []
    dashboard.complianceHolds = []
    dashboard.incomingInstructions = []
    dashboard.finalLegAttempts = []
    dashboard.requeryAttempts = []
    dashboard.outcomeEvidence = []
    dashboard.remediationCases = []
    dashboard.routeDecisions = []
    dashboard.evidenceRequirements = []
    dashboard.reconciliationMatches = []
    dashboard.routeHealthWindows = []
    dashboard.integrationHealth = []
    dashboard.summary.stuckTransactions = 0
    dashboard.summary.activeIncidents = 0
    dashboard.recommendation = {
      ...dashboard.recommendation,
      title: 'No route action needed.',
      trigger: 'All monitored routes are inside policy.',
      affectedTraffic: '0 transfers',
      affectedValue: '$0',
      nextAction: 'Keep monitoring',
      state: 'healthy',
    }
  }

  return dashboard
}
